Repository SensehacK/health-sense, pull requests merged in 2020-04, with the labels that each got.

#18 Documentation WIP
  CONTRIBUTING.md
  README.md
Labels: documentation, help wanted, peer review

#21 Travis ci
  .gitignore
  package-lock.json
  package.json
  src/iOS/HealthSense/.swiftlint.yml
  src/iOS/HealthSense/.travis.yml
  src/iOS/HealthSense/HealthSense WatchKit Extension/ExtensionDelegate.swift
  src/iOS/HealthSense/HealthSense.xcodeproj/xcshareddata/xcschemes/HealthSense WatchKit App (Complication).xcscheme
  src/iOS/HealthSense/HealthSense.xcodeproj/xcshareddata/xcschemes/HealthSense WatchKit App (Notification).xcscheme
  src/iOS/HealthSense/HealthSense.xcodeproj/xcshareddata/xcschemes/HealthSense WatchKit App.xcscheme
  src/iOS/HealthSense/HealthSense.xcodeproj/xcshareddata/xcschemes/HealthSense.xcscheme
  src/iOS/HealthSense/HealthSense.xcodeproj/xcshareddata/xcschemes/HealthSenseCI.xcscheme
  src/iOS/HealthSense/HealthSense.xcworkspace/contents.xcworkspacedata
  src/iOS/HealthSense/HealthSense.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  src/iOS/HealthSense/HealthSense/HealthManager.swift
  src/web/index.js
Labels: CI/CD, feature

#28 Docs Removal
  docs/researchPaper/HealthSense Conf paper.docx
Labels: documentation

#19 Create swift.yml
  .github/workflows/swift.yml
Labels: CI/CD, test

#26 Create LICENSE
  LICENSE
Labels: documentation

#25 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#32 Ios feat healthkit
  src/iOS/HealthSense/HealthSense WatchKit App/Info.plist
  src/iOS/HealthSense/HealthSense.xcodeproj/project.pbxproj
  src/iOS/HealthSense/HealthSense/Controller/ViewController.swift
  src/iOS/HealthSense/HealthSense/Info.plist
  src/iOS/HealthSense/HealthSense/Storyboard/Base.lproj/HealthBook.storyboard
  src/iOS/HealthSense/HealthSense/Storyboard/Base.lproj/Main.storyboard
  src/iOS/HealthSense/HealthSense/Storyboard/Onboarding.storyboard
  src/iOS/HealthSense/HealthSense/Storyboard/Summary.storyboard
  src/iOS/HealthSense/HealthSense/Utilities/Constants.swift
  src/iOS/HealthSense/HealthSense/Utilities/Profile.swift
  src/iOS/HealthSense/HealthSense/Utilities/Settings.swift
  src/iOS/HealthSense/HealthSense/View/HealthBookViewController.swift
  src/iOS/HealthSense/HealthSense/View/OnboardingViewController.swift
  src/iOS/HealthSense/HealthSense/View/SettingsViewController.swift
  src/iOS/HealthSense/HealthSense/View/SummaryViewController.swift
  src/iOS/HealthSense/HealthSense/View/UITabBarViewController.swift
  src/iOS/HealthSense/Settings.storyboard
Labels: code

#38 iOS Launch UX
  src/iOS/HealthSense/HealthSense WatchKit App/Info.plist
  src/iOS/HealthSense/HealthSense.xcodeproj/project.pbxproj
  src/iOS/HealthSense/HealthSense/Controller/HealthBookViewController.swift
  src/iOS/HealthSense/HealthSense/Controller/Onboarding/FirstOnboardingViewController.swift
  src/iOS/HealthSense/HealthSense/Controller/Onboarding/OnboardingViewController.swift
  src/iOS/HealthSense/HealthSense/Controller/Onboarding/SecondOnboardingViewController.swift
  src/iOS/HealthSense/HealthSense/Controller/Onboarding/ThirdOnboardingViewController.swift
  src/iOS/HealthSense/HealthSense/Controller/SettingsViewController.swift
  src/iOS/HealthSense/HealthSense/Controller/SummaryViewController.swift
  src/iOS/HealthSense/HealthSense/Controller/UITabBarViewController.swift
  src/iOS/HealthSense/HealthSense/Controller/ViewController.swift
  src/iOS/HealthSense/HealthSense/Info.plist
  src/iOS/HealthSense/HealthSense/Main/AppDelegate.swift
  src/iOS/HealthSense/HealthSense/Main/SceneDelegate.swift
  src/iOS/HealthSense/HealthSense/Storyboard/Base.lproj/HealthBook.storyboard
  src/iOS/HealthSense/HealthSense/Storyboard/Base.lproj/Main.storyboard
  src/iOS/HealthSense/HealthSense/Storyboard/Onboarding.storyboard
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/AppIcon.appiconset/Contents.json
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/AppLaunch.imageset/Contents.json
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/AppLaunch.imageset/Icon-1024.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/AppLaunch.imageset/Icon-256.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/AppLaunch.imageset/Icon-512.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/Contents.json
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/anonymous.imageset/Contents.json
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/anonymous.imageset/icons8-anonymous-mask-30.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/anonymous.imageset/icons8-anonymous-mask-60.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/anonymous.imageset/icons8-anonymous-mask-90.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/browse.imageset/Contents.json
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/browse.imageset/icons8-health-book-30.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/browse.imageset/icons8-health-book-60.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/browse.imageset/icons8-health-book-90.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/settings.imageset/Contents.json
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/settings.imageset/icons8-settings-30.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/settings.imageset/icons8-settings-60.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Assets.xcassets/settings.imageset/icons8-settings-90.png
  src/iOS/HealthSense/HealthSense/Supporting Files/Base.lproj/LaunchScreen.storyboard
  src/iOS/HealthSense/HealthSense/Utilities/Analytics.swift
  src/iOS/HealthSense/HealthSense/Utilities/Constants.swift
  src/iOS/HealthSense/HealthSense/Utilities/Profile.swift
  src/iOS/HealthSense/HealthSense/Utilities/Settings.swift
  src/iOS/HealthSense/HealthSense/Utilities/User.swift
Labels: feature

#41 Feat healthkit phase1
  src/iOS/HealthSense/HealthSense WatchKit App/Info.plist
  src/iOS/HealthSense/HealthSense.xcodeproj/project.pbxproj
  src/iOS/HealthSense/HealthSense/Controller/SettingsViewController.swift
  src/iOS/HealthSense/HealthSense/Controller/SummaryViewController.swift
  src/iOS/HealthSense/HealthSense/HealthManager.swift
  src/iOS/HealthSense/HealthSense/Helper/Healthkit/ReadProfile.swift
  src/iOS/HealthSense/HealthSense/Helper/Helper.swift
  src/iOS/HealthSense/HealthSense/Info.plist
  src/iOS/HealthSense/HealthSense/Storyboard/Summary.storyboard
  src/iOS/HealthSense/HealthSense/Utilities/User.swift
  src/iOS/HealthSense/README.md
  src/iOS/HealthSense/Settings.storyboard
Labels: feature, peer review
